
####### Common Role Variables ########

## System configuration
include_optional_battery_tools: true

## Git configuration
git_email: leandrohenrique.lf@gmail.com 
git_name: Coelhomatias

## Dotfiles
dotfiles_repo: https://github.com/Coelhomatias/.dotfiles.git
dotfiles_branch: hyprland

## Applications
# Every field can be a string or a list of strings
# Leave empty if you don't want to install the application
terminal_emulator: foot
terminal_theme: catppuccin
shell: zsh
shell_prompt: powerlevel10k
shell_theme: catppuccin

####### Desktop Role Variables ########

window_manager: hyprland
display_manager: sddm


####### App Role Variables ########

file_manager: thunar
text_editor: nvim
web_browser: firefox

