- name: Apply all roles
  hosts: localhost
  roles:
    - common
    - desktop
    - apps

- name: Reboot the machine
  hosts: localhost
  become: yes
  tasks:
    - name: Reboot the machine
      shell: ( sleep 10 ; reboot ) & 
      async: 1
      poll: 0
      ignore_errors: yes