- name: Install sddm display manager
  pacman:
    name: sddm
    state: present
  become: yes
  when: display_manager == "sddm"

- name: Enable sddm service
  shell: systemctl enable sddm
  become: yes
  when: display_manager == "sddm"