- name: Install Hyperland
  pacman:
    name: hyprland
    state: present
  become: yes

- name: Install ags and hyprpicker
  kewlfft.aur.aur:
   use: paru
   name: 
    - aylurs-gtk-shell
    - hyprpicker
   state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"
  