- name: Update package list and upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install hyprland
  include_tasks: hyprland.yml
  when: window_manager == "hyprland"

- name: Install display manager
  include_tasks: display_managers.yml
  when: display_manager is defined

- include_tasks: themes.yml