- name: Enable the bluetooth service
  systemd:
    name: bluetooth
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Mask systemd-rfkill.service
  systemd:
    name: systemd-rfkill
    masked: yes
    state: stopped
    daemon_reload: yes
  become: yes

- name: Mask systemd-rfkill.socket
  systemd:
    name: systemd-rfkill.socket
    masked: yes
    state: stopped
    daemon_reload: yes
  become: yes

- name: Enable pipewire service
  systemd:
    name: pipewire
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Enable pipewire-pulse service 
  systemd:
    name: pipewire-pulse
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Enable the docker.socket service
  systemd:
    name: docker.socket
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Add user to the video group
  user:
    name: "{{ ansible_env.USER }}"
    groups: video
    append: yes
  become: yes
