- name: Enable the bluetooth service
  systemd:
    name: bluetooth
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Enable sshd service
  systemd:
    name: sshd
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes
  listen: Enable battery management tools

- name: Mask systemd-rfkill.service
  systemd:
    name: systemd-rfkill
    masked: yes
    state: stopped
    daemon_reload: yes
  become: yes
  listen: Enable battery management tools

- name: Mask systemd-rfkill.socket
  systemd:
    name: systemd-rfkill.socket
    masked: yes
    state: stopped
    daemon_reload: yes
  become: yes
  listen: Enable battery management tools

- name: Enable pipewire service
  shell: systemctl --user enable --now pipewire
  become: yes
  become_user: "{{ ansible_env.USER }}"
  listen: Enable audio services

- name: Enable pipewire-pulse service
  shell: systemctl --user enable --now pipewire-pulse
  become: yes
  become_user: "{{ ansible_env.USER }}"
  listen: Enable audio services

- name: Enable the docker.socket service
  systemd:
    name: docker.socket
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Add user to the video group
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - video
      - input
    append: yes
  become: yes

- name: Rebuild bat's cache
  shell: bat cache --build
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Stow the dotfiles
  shell: cd /home/{{ ansible_env.USER }}/.dotfiles && stow --adopt .
  become: yes
  become_user: "{{ ansible_env.USER }}"
  listen: Dotfiles

- name: Apply GTK themes
  shell: nwg-look -a
  become: yes
  become_user: "{{ ansible_env.USER }}"
  listen: Dotfiles

- name: Restore git repo
  shell: cd /home/{{ ansible_env.USER }}/.dotfiles && git restore .
  become: yes
  become_user: "{{ ansible_env.USER }}"
  listen: Dotfiles

- name: Rebuid the font cache
  shell: fc-cache -f -v
  become: yes
  become_user: "{{ ansible_env.USER }}"
  listen: Rebuild font cache
