- name: Install apps from pacman
  pacman:
    name: 
      - spotify-launcher
      - code
      - discord
      - obsidian
      - rclone
      - yazi
      - neovim
    state: present
  become: yes

- name: Install thunar file manager
  pacman:
    name: 
      - thunar
      - gvfs
      - gvfs-mtp
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - tumbler
      - thunar-volman
    state: present
  become: yes

- name: Install apps from AUR
  kewlfft.aur.aur:
    use: paru
    name: 
      - microsoft-edge-stable-bin
      - brave-bin
      - skypeforlinux-bin
      - teams-for-linux-bin
      - teams-for-linux-wayland-hook
      - nchat-git
      - vlc-git
      - zapzap
      - toipe
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"