- name: Install apps from pacman
  pacman:
    name:
      - code
      - vlc
      - rclone
      - yazi
      - neovim
      - easyeffects
    state: present
  become: yes

- name: Install flatpaks
  flatpak:
    name:
      - com.spotify.Client
      - com.discordapp.Discord
      - md.obsidian.Obsidian
      - com.microsoft.Edge
      - com.brave.Browser
      - com.skype.Client
      - com.rtosta.zapzap
      - com.github.tchx84.Flatseal
      - com.stremio.Stremio
      - io.github.flattool.Warehouse
      - io.github.giantpinkrobots.flatsweep
    state: present

- name: Install thunar file manager
  pacman:
    name:
      - thunar
      - gvfs
      - gvfs-mtp
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - tumbler
      - thunar-volman
    state: present
  become: yes

- name: Install apps from AUR
  kewlfft.aur.aur:
    use: paru
    name:
      - skypeforlinux-bin
      - teams-for-linux-bin
      - teams-for-linux-wayland-hook
      - nchat-git
      - toipe
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"
