- name: Install kora icon theme
  kewlfft.aur.aur:
    use: paru
    name:  kora-icon-theme
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Install volates cursors
  kewlfft.aur.aur:
    use: paru
    name: 
      - volantes-cursors-git
      - catppuccin-cursors-mocha
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"