- name: Clone the dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: /home/{{ ansible_env.USER }}/.dotfiles
    single_branch: yes
    version: "{{ dotfiles_branch }}"
  become: yes
  become_user: "{{ ansible_env.USER }}"
  notify: Dotfiles

- name: Apply Gtk theme using nwg-look
  shell: nwg-look -a
  become: yes
  become_user: "{{ ansible_env.USER }}"
