- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: '{{ git_email }}'
  become: yes
  become_user: '{{ ansible_env.USER }}'

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: '{{ git_name }}'
  become: yes
  become_user: '{{ ansible_env.USER }}'
