- name: Install paru using AUR
  kewlfft.aur.aur:
    name: paru
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Install linux-headers
  pacman:
    name:
      - linux-headers
      - base-devel
    state: present
  become: yes

- name: Install openssh
  pacman:
    name: openssh
    state: present
  become: yes
  notify: Enable sshd service

- name: Install sound packages
  pacman:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - pamixer
      - wireplumber
      - pavucontrol
    state: present
  become: yes
  notify: Enable audio services

- name: Install bluetooth packages
  pacman:
    name:
      - bluez
      - bluez-utils
      - blueman
      - bc
      - gnome-bluetooth-3.0
    state: present
  notify: Enable the bluetooth service
  become: yes

- name: Install battery management packages
  pacman:
    name:
      - tlp
      - tlp-rdw
      - upower
    state: present
  become: yes
  notify: Enable battery management tools

- name: Install optional battery management tools (powertop)
  pacman:
    name:
      - powertop
    state: present
  when: include_optional_battery_tools | default(true)
  become: yes

- name: Install xsettingsd
  pacman:
    name: xsettingsd
    state: present
  become: yes

- name: Install xdg-user-dirs
  pacman:
    name: xdg-user-dirs
    state: present
  become: yes

- name: Install xdg-utils
  pacman:
    name: xdg-utils
    state: present
  become: yes

- name: Install system utils
  pacman:
    name:
      - lm_sensors
      - trash-cli
      - gnome-bluetooth-3.0
      - gnome-keyring
    state: present
  become: yes
