- name: Install selected terminal emulator(s)
  pacman:
    name: "{{ terminal_emulator }}"
    state: present
  when: terminal_emulator is defined
  become: yes

- name: Install zsh
  pacman:
    name: zsh
    state: present
  when: shell == "zsh"
  become: yes

- name: Set zsh as default shell
  shell: chsh -s $(which zsh) "{{ ansible_env.USER }}"
  when: shell == "zsh"
  become: yes

- name: Install zsh plugins
  pacman:
    name:
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-completions
    state: present
  when: shell == "zsh"
  become: yes

- name: Install zsh-you-should-use
  kewlfft.aur.aur:
    use: paru
    name: zsh-you-should-use
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"
  when: shell == "zsh"

- name: Install powerlevel10k
  kewlfft.aur.aur:
    use: paru
    name: zsh-theme-powerlevel10k-git
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"
  when: shell_prompt == "powerlevel10k"

- name: Install xdg-terminal-exec
  kewlfft.aur.aur:
    use: paru
    name: xdg-terminal-exec-git
    state: present
  become: yes
  become_user: "{{ ansible_env.USER }}"
  when: terminal_emulator is defined
