- name: Ensure the Alacritty configuration directory exists
  file:
    path: /home/{{ ansible_env.USER }}/.config/alacritty
    state: directory
  when: terminal_emulator == "alacritty"
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Ensure the Alacritty themes directory exists
  file:
    path: /home/{{ ansible_env.USER }}/.config/alacritty/themes
    state: directory
  when: terminal_emulator == "alacritty"
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Download catppuccin theme for Alacritty
  get_url:
    url: https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
    dest: /home/{{ ansible_env.USER }}/.config/alacritty/themes/catppuccin-mocha.toml
  when: terminal_theme == "catppuccin" and terminal_emulator == "alacritty"
  become: yes
  become_user: "{{ ansible_env.USER }}"


