- name: Install terminal utils
  pacman:
    name:
      - eza
      - jq
      - ffmpegthumbnailer
      - network-manager-applet
      - flameshot
      - tmux
      - poppler
      - zoxide
      - fzf
      - ripgrep
      - bat
      - fd
      - bc
      - brightnessctl
      - btop
      - git-delta
      - unarchiver
      - unzip
      - stow
      - playerctl
      - fastfetch
      - nwg-look
      - man
      - zathura
      - zathura-pdf-poppler
      - zathura-djvu
      - zathura-ps
      - zathura-cb
    state: present
  become: yes
  notify: Rebuild bat's cache

- name: Install terminal utils from AUR
  kewlfft.aur.aur:
    use: paru
    name:
      - tlrc
      - sesh-bin
      - ijq
      - rnr
      - nwg-displays
      - ifstat
      - bluetui
    state: present
  notify: Add user to the video group
  become: yes
  become_user: "{{ ansible_env.USER }}"

