---
- name: Apply common configurations and install common tools
  hosts: localhost
  roles:
    - common

- name: Reboot the machine
  hosts: localhost
  become: yes
  tasks:
    - name: Reboot the machine
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible playbook"
        reboot_timeout: 600
