---
- name: Apply all roles
  hosts: localhost
  become: yes
  roles:
    - common
    - desktop
    - apps

- name: Reboot the machine
  hosts: localhost
  become: yes
  tasks:
    - name: Reboot the machine
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible playbook"
        reboot_timeout: 600
